# Generated by Django 5.0.3 on 2024-03-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_image_remove_product_image_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default='default_image.jpg', upload_to='store/'),
        ),
    ]
