# Generated by Django 5.0.3 on 2024-03-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_images_delete_image_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='images1',
            field=models.ImageField(default='default_image.jpg', upload_to='store/images.costumers/'),
        ),
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(default='default_image.jpg', upload_to='store/images.costumers/'),
        ),
        migrations.AddField(
            model_name='product',
            name='images3',
            field=models.ImageField(default='default_image.jpg', upload_to='store/images.costumers/'),
        ),
    ]
