# Generated by Django 5.0.3 on 2024-03-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_images_product_images1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images1',
            field=models.ImageField(default='default_image.jpg', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images2',
            field=models.ImageField(default='default_image.jpg', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images3',
            field=models.ImageField(default='default_image.jpg', upload_to='static/images/'),
        ),
    ]
