# Generated by Django 5.0.3 on 2024-03-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_mobileness_product_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mobileness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='office',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
